import argparse
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import shutil
import tempfile
import zipfile
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
INTERFACE_VERSION = "nilm_model_interface_v1"
REQUIRED_FILES = [
    "model.onnx",
    "model_meta.json",
    "normalization.json",
    "postprocess.json",
]


def sha256_file(path: Path, chunk_size: int = 1024 * 1024) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        while True:
            b = f.read(chunk_size)
            if not b:
                break
            h.update(b)
    return h.hexdigest()


def load_json(path: Path) -> dict[str, Any]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        # Allow BOM-encoded json generated by certain Windows commands.
        return json.loads(path.read_text(encoding="utf-8-sig"))


def require_keys(data: dict[str, Any], keys: list[str], name: str) -> None:
    missing = [k for k in keys if k not in data]
    if missing:
        raise ValueError(f"{name} missing required keys: {missing}")


def validate_contract(
    meta: dict[str, Any],
    norm: dict[str, Any],
    rules: dict[str, Any],
) -> None:
    require_keys(
        meta,
        [
            "model_name",
            "dataset",
            "sample_period_s",
            "window_size",
            "appliances",
            "input_name",
            "output_name",
            "input_shape",
            "output_shape",
        ],
        "model_meta.json",
    )
    require_keys(
        norm,
        ["mains_mean", "mains_std", "target_mean", "target_std"],
        "normalization.json",
    )
    require_keys(
        rules,
        ["on_threshold_w", "off_threshold_w", "min_on_seconds", "min_off_seconds"],
        "postprocess.json",
    )

    apps = list(meta["appliances"])
    if not apps:
        raise ValueError("model_meta.appliances must not be empty")
    for app in apps:
        if app not in norm["target_mean"] or app not in norm["target_std"]:
            raise ValueError(f"normalization missing appliance stats for: {app}")
        if app not in rules["on_threshold_w"] or app not in rules["off_threshold_w"]:
            raise ValueError(f"postprocess thresholds missing appliance: {app}")


def build_interface_spec(
    artifact_id: str,
    meta: dict[str, Any],
    rules: dict[str, Any],
) -> dict[str, Any]:
    return {
        "interface_version": INTERFACE_VERSION,
        "artifact_id": artifact_id,
        "model_type": "seq2point_multi_output",
        "io": {
            "input_name": meta["input_name"],
            "output_name": meta["output_name"],
            "input_dtype": "float32",
            "output_dtype": "float32",
            "input_shape": meta["input_shape"],
            "output_shape": meta["output_shape"],
            "layout": {
                "input": "[batch, time, channel]",
                "output": "[batch, appliance]",
            },
        },
        "semantics": {
            "sample_period_s": float(meta["sample_period_s"]),
            "window_size": int(meta["window_size"]),
            "appliances_order": list(meta["appliances"]),
        },
        "pipeline": {
            "preprocess": [
                "Normalize mains with normalization.json: (x - mains_mean) / mains_std",
            ],
            "postprocess": [
                "Denormalize output with target_mean/target_std from normalization.json",
                "If postprocess.linear_calibration exists, apply y=max(0, scale_a*y+bias_b) per appliance",
                "Extract events with thresholds and min_on/off seconds from postprocess.json",
            ],
        },
        "swap_compatibility": {
            "must_match": [
                "interface_version",
                "input tensor rank and dtype",
                "output tensor rank and dtype",
                "sample_period_s expected by caller",
            ],
            "should_match": [
                "appliances_order",
                "window_size",
            ],
        },
        "notes": {
            "has_linear_calibration": bool("linear_calibration" in rules),
        },
    }


def zip_dir(src_dir: Path, dst_zip: Path) -> None:
    with zipfile.ZipFile(dst_zip, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        for p in sorted(src_dir.rglob("*")):
            if p.is_file():
                arcname = p.relative_to(src_dir)
                zf.write(p, arcname=str(arcname))


def main() -> None:
    parser = argparse.ArgumentParser(description="Export standardized model package zip.")
    parser.add_argument("--artifact-id", required=True, help="Source artifact directory name under artifacts/models")
    parser.add_argument("--profile", default="custom", help="e.g. event_optimized / error_optimized / balanced")
    parser.add_argument("--out-dir", default="artifacts/packages")
    parser.add_argument("--package-name", default="", help="Default: <artifact-id>__<profile>")
    parser.add_argument("--include-reports", action="store_true", help="Include optional report json files")
    args = parser.parse_args()

    artifact_dir = (ROOT / "artifacts" / "models" / args.artifact_id).resolve()
    if not artifact_dir.exists():
        raise FileNotFoundError(f"Artifact not found: {artifact_dir}")

    for fn in REQUIRED_FILES:
        p = artifact_dir / fn
        if not p.exists():
            raise FileNotFoundError(f"Required file missing in artifact: {p}")

    meta = load_json(artifact_dir / "model_meta.json")
    norm = load_json(artifact_dir / "normalization.json")
    rules = load_json(artifact_dir / "postprocess.json")
    validate_contract(meta, norm, rules)

    interface_spec = build_interface_spec(args.artifact_id, meta, rules)
    package_name = args.package_name.strip() or f"{args.artifact_id}__{args.profile}"

    out_dir = Path(args.out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    zip_path = out_dir / f"{package_name}.zip"

    optional_files = []
    if args.include_reports:
        for fn in [
            "onnx_parity_check.json",
            "calibration_report.json",
            "threshold_optimization_report.json",
            "linear_calibration.json",
            "combo_note.json",
            "fridge_boost_report.json",
        ]:
            p = artifact_dir / fn
            if p.exists():
                optional_files.append(fn)

    with tempfile.TemporaryDirectory(prefix="model_pkg_") as tmp:
        tmp_dir = Path(tmp)
        for fn in REQUIRED_FILES:
            shutil.copy2(artifact_dir / fn, tmp_dir / fn)
        for fn in optional_files:
            shutil.copy2(artifact_dir / fn, tmp_dir / fn)

        (tmp_dir / "interface_spec.json").write_text(
            json.dumps(interface_spec, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )

        manifest_files = REQUIRED_FILES + optional_files + ["interface_spec.json"]
        manifest_entries = []
        for fn in manifest_files:
            p = tmp_dir / fn
            manifest_entries.append(
                {
                    "path": fn,
                    "bytes": int(p.stat().st_size),
                    "sha256": sha256_file(p),
                }
            )

        manifest = {
            "package_format_version": "1.0.0",
            "created_at_utc": datetime.now(timezone.utc).isoformat(),
            "artifact_id": args.artifact_id,
            "profile": args.profile,
            "interface_version": INTERFACE_VERSION,
            "files": manifest_entries,
        }
        (tmp_dir / "package_manifest.json").write_text(
            json.dumps(manifest, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )

        zip_dir(tmp_dir, zip_path)

    print(f"Source artifact : {artifact_dir}")
    print(f"Package zip     : {zip_path}")
    print(f"Interface ver   : {INTERFACE_VERSION}")
    print(f"Profile         : {args.profile}")


if __name__ == "__main__":
    main()
